Add replay tool
cogip/simulation pull request #15
Opened 2021-06-01 19:55 UTC by ecourtois

Adapt the simulator to new trace thread of mcu-firmware.
Optimize buoys by replacing them by cone entities.
Add the replay tool to replay a game saved in a trace file.

2021-06-01 19:57 UTC, ecourtois commented
A trace file example to play with the new tool :
[TRACE.TXT](https://github.com/cogip/simulation/files/6580281/TRACE.TXT)

2021-06-03 18:35 UTC, gdoffe requested changes
https://github.com/cogip/simulation/pull/15/commits/2d51e13f0ddfd9f8122f735dea989cc9aaa92dde
"The input **is** parsed into"

2021-06-03 18:35 UTC, gdoffe commented on cogip/tools/replay/__main__.py
> +
you can remove one empty line.

2021-06-03 18:49 UTC, gdoffe approved these changes
LGTM ! nice job !

2021-06-03 19:19 UTC, merged