Add documentation
cogip/simulation pull request #6
Opened 2020-10-03 22:38 UTC by ecourtois

Add user and developer documentation.
Use mkdocs to build the documentation.
Add github action to publish the doc when pushing on master.

2020-10-06 20:07 UTC, gdoffe requested changes

2020-10-06 20:07 UTC, gdoffe commented on cogip/mainwindow.py
> +        Update information robot position in the status bar.
Update robot position information

2020-10-06 20:15 UTC, gdoffe commented
Can you also activate the 'search' mkdocs plugin on your pages ?

2020-10-11 17:03 UTC, ecourtois commented on cogip/assetentity.py
> +It's typically used for table and robot assets.
Done

2020-10-11 17:03 UTC, ecourtois commented on cogip/obstacleentity.py
> +        If this event occurs juste after a ```pressed``` event, it's only a mouse click,
Done

2020-10-11 17:04 UTC, ecourtois commented on cogip/assetentity.py
> +        The entity load is asynchronous, a signal is emitted when it's done
Done

2020-10-11 17:04 UTC, ecourtois commented on docs/developers/developers.md
> +To have a better understanding of the code, it's important to Qt concepts
Done

2020-10-11 17:04 UTC, ecourtois commented on docs/developers/developers.md
> +To have a better understanding of the code, it's important to Qt concepts
Done

2020-10-11 17:04 UTC, ecourtois commented on docs/install.md
> +!!! note "Python 3.8 or more is required."
Done

2020-10-11 17:04 UTC, ecourtois commented on docs/usage.md
> +If no serial port is found, it will launch the default native firmware (see [Native Mode](#native-mode)).
Done

2020-10-11 17:04 UTC, ecourtois commented on cogip/assetentity.py
> +        Generated a tree of all entities and components starting from the main entity.
Done

2020-10-11 17:04 UTC, ecourtois commented on cogip/mainwindow.py
> +        Update information robot position in the status bar.
Done

2020-10-18 09:55 UTC, gdoffe approved these changes

2020-10-18 09:58 UTC, merged